/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: structurs.proto */

#ifndef PROTOBUF_C_structurs_2eproto__INCLUDED
#define PROTOBUF_C_structurs_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _UserStructur UserStructur;


/* --- enums --- */


/* --- messages --- */

struct  _UserStructur
{
  ProtobufCMessage base;
  uint32_t id;
  uint32_t years;
  uint64_t crc;
};
#define USER_STRUCTUR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&user_structur__descriptor) \
    , 0, 0, 0 }


/* UserStructur methods */
void   user_structur__init
                     (UserStructur         *message);
size_t user_structur__get_packed_size
                     (const UserStructur   *message);
size_t user_structur__pack
                     (const UserStructur   *message,
                      uint8_t             *out);
size_t user_structur__pack_to_buffer
                     (const UserStructur   *message,
                      ProtobufCBuffer     *buffer);
UserStructur *
       user_structur__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   user_structur__free_unpacked
                     (UserStructur *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*UserStructur_Closure)
                 (const UserStructur *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor user_structur__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_structurs_2eproto__INCLUDED */
