/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: structurs_v2.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "structurs_v2.pb-c.h"
void   amessage_3__init
                     (AMessage3         *message)
{
  static const AMessage3 init_value = AMESSAGE_3__INIT;
  *message = init_value;
}
size_t amessage_3__get_packed_size
                     (const AMessage3 *message)
{
  assert(message->base.descriptor == &amessage_3__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t amessage_3__pack
                     (const AMessage3 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &amessage_3__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t amessage_3__pack_to_buffer
                     (const AMessage3 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &amessage_3__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AMessage3 *
       amessage_3__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AMessage3 *)
     protobuf_c_message_unpack (&amessage_3__descriptor,
                                allocator, len, data);
}
void   amessage_3__free_unpacked
                     (AMessage3 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &amessage_3__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor amessage_3__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(AMessage3, has_id),
    offsetof(AMessage3, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "crc",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(AMessage3, has_crc),
    offsetof(AMessage3, crc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned amessage_3__field_indices_by_name[] = {
  1,   /* field[1] = crc */
  0,   /* field[0] = id */
};
static const ProtobufCIntRange amessage_3__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 3, 1 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor amessage_3__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AMessage_3",
  "AMessage3",
  "AMessage3",
  "",
  sizeof(AMessage3),
  2,
  amessage_3__field_descriptors,
  amessage_3__field_indices_by_name,
  2,  amessage_3__number_ranges,
  (ProtobufCMessageInit) amessage_3__init,
  NULL,NULL,NULL    /* reserved[123] */
};
